version: 2

requirements:
  signed_off_by:
    required: true

always_pending:
  title_regex: 'WIP'

group_defaults:
  approve_by_comment:
    enabled: true
    approve_regex: ^LGTM
    reject_regex: ^Rejected
  reset_on_push:
    enabled: true
  reviewers:
    teams:
      - isula-maintainers
  required: 1
