version: 2

requirements:
  signed_off_by:
    required: true

always_pending:
  title_regex: 'WIP'

groups:
  code-review:
    approve_by_comment:
      approve_regex: ^Approved
      enabled: true
      reject_regex: ^Rejected
    required: 1
    reset_on_push:
      enabled: true
    teams:
    - isula-maintainers
    
